### ISSUE TITLE
push mean packages to openshift ???

### ISSUE THREAD

**Issue by lleoooell** [linnovate/mean-on-openshift#7]
Hi,

Can somebody knows how to add mean packages (ex : mean-admin; tokens, translate, etc) to openshift?
I'm able to run my app locally (with pain^^) and these packages are well installed in my local dist. I was thinking that gitignore would not consider these packages as they are in node_modules/, so i add !node_modules/tokens to my gitignore files. but push fail...

I don't know how to do... locally, remotely (i try to run the command in the repo also but permission denied...) 
Please, help, i'm desperate...

**Comment by liorkesos** [comment]
Try to add the package you need to mean.json
Look at mean translate for example...
